name: 打包应用

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: 安装依赖
        run: |
          pip install pyinstaller pillow
      
      - name: 打包 macOS 应用
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            --name="海报合成工具" \
            --add-data="README.md:." \
            poster.py
      
      - name: 压缩应用
        run: |
          cd dist
          zip -r 海报合成工具-macOS.zip 海报合成工具.app
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: dist/海报合成工具-macOS.zip
      
      - name: 创建 Release（可选）
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/海报合成工具-macOS.zip
