name: 多平台打包

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact: windows-app
          - os: macos-latest
            artifact: macos-app
          - os: ubuntu-latest
            artifact: linux-app
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: 安装依赖
        run: |
          pip install pyinstaller pillow
      
      - name: 打包应用 (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --windowed --name="海报合成工具" poster.py
      
      - name: 打包应用 (macOS)
        if: runner.os == 'macOS'
        run: |
          pyinstaller --onefile --windowed --name="海报合成工具" poster.py
          cd dist
          zip -r 海报合成工具-macOS.zip 海报合成工具.app
      
      - name: 打包应用 (Linux)
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile --name="海报合成工具" poster.py
      
      - name: 上传 Windows 构建产物
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/*.exe
      
      - name: 上传 macOS 构建产物
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/*.zip
      
      - name: 上传 Linux 构建产物
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: dist/海报合成工具
